config/routes.rb
Rails.application.routes.draw do
  root to: "games#index"
  devise_for :users
  resources :games do
    resources :joins
  end

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :joins,
      -> { extending WithUserAssociationExtension },
      dependent: :restrict_with_exception

  belongs_to :user
  has_many :users

  def has_been_joined?(user)
    joined_by(user).length > 0
  end

  def joined_by(user)
    (joins&user.joins)    
  end
end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :games
  has_many :joined_games, through: :joins, source: :game
  has_many :joins

  def has_joined?(game)
    joined_games.include? game
  end
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @game = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    Game.create(game_params)
    redirect_to '/games'
  end

  def show
    @game = Game.find(params[:id])
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    flash[:notice] = 'Game deleted successfully'
    redirect_to '/games'
  end

  private
  def game_params
    params.require(:game).permit(:name, :location, :date_time)
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController

  def new
    @game = Game.find(params[:game_id])
    create
  end

  def create
    @join = @game.joins.build_with_user(current_user)
    if @join.save
      flash[:notice] = "You have joined #{@game.name}"
      redirect_to games_path
    else
      render :new
    end
  end

  def destroy
    @join = Join.find(params[:id])
    if current_user == @join.user
      @join.destroy
      flash[:notice] = 'You left the game'
    else
      flash[:notice] = 'Cannot leave the game'
    end
    redirect_to '/games'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<% if @game.any? %>
  <% @game.each do |game| %>
  <% if user_signed_in? %>
      <% if current_user.has_joined?(game) %>
        <%= link_to 'Leave Game', game_join_path(game, game.joined_by(current_user)), method: :delete %>
      <% else %>
        <%= link_to 'Join Game', new_game_join_path(game) %>
      <% end %>
      <% end %>

    <h2> <%= link_to game.name, game_path(game) %></h2>
  <% end %>
<% else %>
  No games yet
<% end %>

<%= link_to 'Add a Game', new_game_path %>

app/views/games/new.html.erb
<%= simple_form_for @game do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.input :date_time, as: :datetime_picker, wrapper: :ranged_datetime %>
  <%= f.submit 'Create a game' %>
<% end %>

app/views/games/show.html.erb
<%= @game.name %>
<%= @game.location %>
<%= @game.date_time %>

<% if user_signed_in? %>
  <%= link_to 'Delete Game', game_path(@game), method: :delete %>

  <% if current_user.has_joined?(@game) %>
    <%= link_to 'Leave Game', game_join_path(@game, @game.joined_by(current_user)), method: :delete %>
  <% else %>
    <%= link_to 'Join Game', new_game_join_path(@game) %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FootyFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>